name: Deploy to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install OpenShift CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
        sudo mv oc kubectl /usr/local/bin/
    
    - name: Login to OpenShift
      run: |
        oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
    
    - name: Build and push image
      run: |
        oc project ${{ secrets.OPENSHIFT_PROJECT }}
        oc start-build mrse --from-dir=. --follow
    
    - name: Deploy application
      run: |
        oc rollout latest dc/mrse-app
        oc rollout status dc/mrse-app